src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('login/', views.LoginPage.as_view(), name='login'),
    path('logout/', views.LogoutPage.as_view(), name='logout'),
]

src/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create/room', views.CreateRoom.as_view(), name='create_room'),
    path('update/room/<int:pk>', views.UpdateRoom.as_view(), name='update_room'),
    path('delete/room/<int:pk>', views.DeleteRoom.as_view(), name='delete_room'),
    path('enter/room/<int:pk>', views.EnterRoom.as_view(), name='enter_room'),
    path('update/config/<int:pk>', views.UpdateConfig.as_view(), name='update_config'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('chat/', include('chat.urls', namespace='chat')),
]

src/templates/base.html
<!doctype html>
<html lang="ja">
{% load static %}
<head>
    {# Required meta tags #}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {# Bootstrap CSS #}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css">
    <title>Chat Demo</title>
    {% block header %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'accounts:index' %}">Chat Demo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li>
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">
                        Logout
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">
                        Login
                    </a>
                </li>
            {% endif %}
            </ul>
        </div>
    </nav>
    {# main contents #}
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>
    {# Optional JavaScript #}
    {# jQuery first, then Bootstrap JS (Bundle version) #}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
            integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
    {% block bodyjs %}
    {% endblock %}
</body>
</html>

src/templates/custom_form.html
<div {% if className %}class="{{ className }}"{% endif %}>
    {% if colLabel|default:"" and colForm|default:"" %}
    <label for="{{ field.id_for_label }}" class="{{ colLabel }} col-form-label">
        {{ field.label }}
    </label>
    <div class="{{ colForm }}">
        {{ field }}
    </div>
    {% else %}
    <label for="{{ field.id_for_label }}" class="form-label">
        {{ field.label }}
    </label>
    {{ field }}
    {% endif %}
    {% if field.help_text %}
    <span class="custom-helptext">
        {{ field.help_text }}
    </span>
    {% endif %}

    {% if field.errors %}
    <div class="d-flex flex-column justify-content-left">
        {% for error in field.errors %}
        <div class="text-danger">
            {{ error }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>

src/templates/pagination.html
{% load pagination %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
    {# before #}
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?{%  url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}

    {# number #}
    {% for num in paginator.page_range %}
        {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}
            {% if page_obj.number == num %}
            <li class="page-item active">
                <span class="page-link">
                    {{ num }}
                    <span class="sr-only">(current)</span>
                </span>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?{%  url_replace request 'page' num %}">
                    {{ num }}
                </a>
            </li>
            {% endif %}
        {% endif %}
    {% endfor %}

    {# next #}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?{%  url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>