src/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create/room', views.CreateRoom.as_view(), name='create_room'),
    path('update/room/<int:pk>', views.UpdateRoom.as_view(), name='update_room'),
    path('delete/room/<int:pk>', views.DeleteRoom.as_view(), name='delete_room'),
    path('enter/room/<int:pk>', views.EnterRoom.as_view(), name='enter_room'),
    path('update/config/<int:pk>', views.UpdateConfig.as_view(), name='update_config'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('chat/', include('chat.urls', namespace='chat')),
]

src/chat/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy
import operator
from functools import reduce

User = get_user_model()

class RoomQueryset(models.QuerySet):
    def _related_user(self, user=None):
        try:
            queryset = self.filter(models.Q(host=user) | models.Q(participants__in=[user.pk]))
        except:
            queryset = self

        return queryset

    def filtering(self, user=None, keywords='', order='-created_at'):
        words = keywords.split()
        queryset = self._related_user(user=user)

        if words:
            condition = reduce(operator.or_, (models.Q(name__icontains=word) for word in words))
            queryset = queryset.filter(condition)

        return queryset.order_by(order).distinct()

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(gettext_lazy('Room name'), max_length=64)
    description = models.TextField(gettext_lazy('Description'), max_length=128)
    participants = models.ManyToManyField(User, related_name='rooms', verbose_name=gettext_lazy('Participants'), blank=True)
    created_at = models.DateTimeField(gettext_lazy('Created time'), default=timezone.now)

    objects = RoomQueryset.as_manager()

    def __str__(self):
        return self.__unicode__()
    def __unicode__(self):
        return self.name

    def set_host(self, user=None):
        if user is not None:
            self.host = user

    def is_host(self, user=None):
        return user is not None and self.host.pk == user.pk

    def is_assigned(self, user=None):
        try:
            _ = self.participants.all().get(pk=user.pk)
            return True
        except User.DoesNotExist:
            return self.host == user
        except Exception:
            return False

class Config(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='configs')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='configs')
    order = models.IntegerField(gettext_lazy('Order'), validators=[MinValueValidator(1)], default=1)
    offset = models.IntegerField(gettext_lazy('Offset'), validators=[MinValueValidator(0), MaxValueValidator(10)], default=0)

    def __str__(self):
        return self.__unicode__()
    def __unicode__(self):
        return str(self.owner)

class MessageManager(models.Manager):
    def ordering(self, order='created_at'):
        return self.get_queryset().order_by(order)

class Message(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='messages')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages')
    content = models.TextField(gettext_lazy('Content'))
    created_at = models.DateTimeField(gettext_lazy('Created time'), default=timezone.now)

    objects = MessageManager()

    def __str__(self):
        return self.__unicode__()
    def __unicode__(self):
        name = str(self.owner)
        text = self.content[:32]

        return f'{name}:{text}'

src/chat/forms.py
from django import forms
from django.utils.translation import gettext_lazy
from . import models

User = models.User

class SearchForm(forms.Form):
    keywords = forms.CharField(
        label=gettext_lazy('keywords (split space)'),
        required=False,
        widget=forms.TextInput(attrs={
            'placeholder': gettext_lazy('Enter the room name.'),
            'class': 'form-control',
        }),
    )

    def get_keywords(self):
        init_keywords = ''
        keywords = init_keywords

        if self.is_valid():
            keywords = self.cleaned_data.get('keywords', init_keywords)

        return keywords

class RoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = ('name', 'description', 'participants')
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': gettext_lazy('Enter the room name.'),
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'rows': 5,
                'cols': 10,
                'style': 'resize: none',
                'placeholder': gettext_lazy('Enter the description.'),
                'class': 'form-control',
            }),
            'participants': forms.SelectMultiple(attrs={
                'class': 'form-control',
            }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['participants'].queryset = User.objects.filter(is_staff=False)

class _ConfigForm(forms.ModelForm):
    class Meta:
        model = models.Config
        fields = ('owner', 'order', 'offset')
        labels = {
            'order': gettext_lazy('Ordering'),
            'offset': gettext_lazy('Offset'),
        }
        widgets = {
            'owner': forms.HiddenInput(),
            'order': forms.NumberInput(attrs={
                'placeholder': gettext_lazy('Enter the ordering'),
                'class': 'form-control',
                'min': '1',
                'step': '1',
            }),
            'offset': forms.NumberInput(attrs={
                'placeholder': gettext_lazy('Enter the offset'),
                'class': 'form-control',
                'min': '0',
                'max': '10',
                'step': '1',
            }),
        }

class _BaseConfigFormSet(forms.BaseModelFormSet):
    def clean(self):
        super().clean()

        # if errors exist, this process is interruptedinterrupted
        if any(self.errors):
            return

        orders = [form.cleaned_data.get('order') for form in self.forms if form not in self.deleted_forms]
        uniq = set(orders)

        if len(orders) != len(uniq):
            raise forms.ValidationError(gettext_lazy("Set the participant's order to uniquely determine the move number."))

ConfigFormSet = forms.modelformset_factory(model=models.Config, form=_ConfigForm, formset=_BaseConfigFormSet, extra=0, max_num=0)

src/chat/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from . import models, forms

class Index(LoginRequiredMixin, ListView):
    model = models.Room
    template_name = 'chat/index.html'
    context_object_name = 'rooms'
    pagenate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        form = forms.SearchForm(self.request.GET or None)
        keywords = form.get_keywords()

        return queryset.filtering(user=self.request.user, keywords=keywords)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = forms.SearchForm(self.request.GET or None)

        return context

class CreateRoom(LoginRequiredMixin, CreateView):
    model = models.Room
    template_name = 'chat/room_form.html'
    form_class = forms.RoomForm
    success_url = reverse_lazy('chat:index')

    def form_valid(self, form):
        form.instance.set_host(self.request.user)
 
        return super().form_valid(form)

class OnlyRoomHostMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        room = self.get_object()

        return room.is_host(self.request.user)

class UpdateRoom(LoginRequiredMixin, OnlyRoomHostMixin, UpdateView):
    model = models.Room
    template_name = 'chat/room_form.html'
    form_class = forms.RoomForm
    success_url = reverse_lazy('chat:index')

class DeleteRoom(LoginRequiredMixin, OnlyRoomHostMixin, DeleteView):
    model = models.Room
    success_url = reverse_lazy('chat:index')

    def get(self, request, *args, **kwargs):
        # ignore direct access
        return self.handle_no_permission()

class OnlyAssignedUserMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        room = self.get_object()

        return room.is_assigned(self.request.user)

class EnterRoom(LoginRequiredMixin, OnlyAssignedUserMixin, DetailView):
    model = models.Room
    template_name = 'chat/chat_room.html'
    context_object_name = 'room'

class UpdateConfig(LoginRequiredMixin, OnlyRoomHostMixin, UpdateView):
    raise_exception = True
    model = models.Room
    form_class = forms.ConfigFormSet
    template_name = 'chat/config_form.html'
    context_object_name = 'room' # Do not use this object in this template
    success_url = reverse_lazy('chat:index')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['queryset'] = kwargs['instance'].configs.all().order_by('order')
        del kwargs['instance']

        return kwargs

    def form_valid(self, form):
        form.save()

        return super().form_valid(form)

    def get_success_url(self):
        return self.success_url

src/templates/chat/chat_room.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-12">
        <div class="row">
            <div class="col-12 col-md-10">
                <h3 class="h3">Chat Room -{{ room|stringformat:"s" }}-</h3>
            </div>
            <div class="col-12 col-md-2">
                <a href="{% url 'chat:index' %}" class="btn btn-outline-secondary btn-block">Back</a>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-12">
                <textarea placeholder="Enter the message" id="chat-message-input" rows="5" class="form-control" style="resize: none;"></textarea>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <button type="submit" id="submit-chat-message" class="btn btn-primary btn-block">Send (Ctrl + Enter)</button>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-left mt-3">
    {% for conf in room.configs.all|dictsort:"order" %}
    <div class="col-6">
        <span>{{ conf.owner|stringformat:"s" }}</span>
        <span>(order: {{ conf.order }}, offset: {{ conf.offset }})</span>
    </div>
    {% endfor %}
</div>
<div class="row justify-content-center mt-3">
    <div class="col-12">
        <div id="chat-log">
            {% for message in room.messages.ordering %}
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <span class="card-username">{{ message.owner|stringformat:"s" }}</span>
                            <time class="card-datetime" datetime="{{ message.created_at|date:'Y-m-d' }}">(created at {{ message.created_at|date:'Y-m-d H:i:s' }})</time>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 card-content">
                            {{ message.content|linebreaksbr }}
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            {% endfor %}
        </div>
    </div>
</div>

<template id="card-template">
    <div class="card">
        <div class="card-body card-font">
            <div class="row">
                <div class="col-12">
                    <span class="card-username"></span>
                    <time class="card-datetime" datetime=""></time>
                </div>
            </div>
            <div class="row">
                <div class="col-12 card-content"></div>
            </div>
        </div>
    </div>
</template>
{% endblock %}

{% block bodyjs %}
<script>
(function() {
    let g_socket = undefined;

    // setup message
    const chatMessageInput = document.querySelector('#chat-message-input');
    const submitChatMessage = document.querySelector('#submit-chat-message');
    submitChatMessage.addEventListener('click', (event) => {
        const message = chatMessageInput.value.trim();

        if (g_socket && message && message.match(/\S/g)) {
            const data = {
                content: message,
            };
            g_socket.send(JSON.stringify(data));
            chatMessageInput.value = '';
        }
    });

    chatMessageInput.focus();
    chatMessageInput.addEventListener('keyup', (event) => {
        // Check Ctrl key and Enter key
        if (event.ctrlKey && (event.key === 'Enter')) {
            submitChatMessage.click();
        }
    });

    // initialization
    const init = () => {
        // create websocket
        const wsScheme = (window.location.protocol === 'https:' ? 'wss' : 'ws');
        const hostname = window.location.host;
        const roomID = '{{ room.pk }}';
        const url = `${wsScheme}://${hostname}/ws/chat/${roomID}`;
        g_socket = new WebSocket(url);

        // message received
        g_socket.onmessage = (event) => {
            const data = JSON.parse(event.data);
            const template = document.querySelector('#card-template');
            const node = template.content.cloneNode(true);
            const isSystem = (data.type !== 'user_message');
            const fontColor = isSystem ? 'red' : 'black';
            // setup target node
            node.querySelector('.card-font').style.color = fontColor;
            node.querySelector('.card-username').textContent = data.username;
            node.querySelector('.card-datetime').textContent = data.datetime;
            node.querySelector('.card-datetime').setAttribute('datetime', data.datetime);
            node.querySelector('.card-content').textContent = data.content;
            document.querySelector('#chat-log').appendChild(node);
        };
        g_socket.onerror = (event) => {
            console.log(event);
        };
        g_socket.onclose = (event) => {
            ;
        };
    };

    document.addEventListener('DOMContentLoaded', init);
}());
</script>
{% endblock %}

src/templates/chat/config_form.html
{% extends 'base.html' %}
{% load chat_utils %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-12">
    <form method="POST">
      {% csrf_token %}

      {% if form.non_form_errors %}
      <div class="mb-2 d-flex flex-column justify-content-left">
        {% for error in form.non_form_errors %}
        <div class="text-danger">
          <label>Error:</label><span>{{ error }}</span>
        </div>
        {% endfor %}
      </div>
      {% endif %}

      {{ form.management_form }}
      <div class="row">
        <div class="col-12">
          {% for item in form %}
            <div class="row mt-2">
              <div class="col-12">
                <label for="{{ item.owner.id_for_label }}" class="form-label">
                  {% with owner=item.owner|conv_fkey2user %}
                      <u>{{ item.owner.label }}: <span>{{ owner|stringformat:"s" }}</span></u>
                  {% endwith %}
                </label>
                {{ item.owner }}
              </div>
            </div>
            <div class="row">
              {% include 'custom_form.html' with field=item.order className="col-6" %}
              {% include 'custom_form.html' with field=item.offset className="col-6" %}
              <div>
                {{ item.id }}
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-12">
          <hr />
        </div>
      </div>
      <div class="row mt-2">
          <div class="col-6">
              <button type="submit" class="btn btn-primary btn-block">Register/Update</button>
          </div>
          <div class="col-6">
              <a href="{% url 'chat:index' %}" class="btn btn-secondary btn-block">Cancel</a>
          </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

src/templates/chat/index.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Filtering</h5>
                <form action="", method="GET">
                    <div class="form-group row">
                        <div class="col-12">
                            {{ search_form.keywords }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                            <button type="submit" class="btn btn-primary btn-block">Search</button>
                        </div>
                        <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                            <a href="{% url 'chat:index' %}" class="btn btn-secondary btn-block">Output all</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Create room</h5>
                <div class="row">
                    <div class="col-12">
                        <a href="{% url 'chat:create_room' %}" class="btn btn-success btn-block">Create</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-center mt-3">
    <div class="col-12">
        <section>
        {% for room in rooms %}
            <article>
                <div class="row">
                    <div class="col-8">
                        <h4 class="h4 mt-1"><a href="{% url 'chat:enter_room' room.pk %}">{{ room.name }}</a></h4>
                        <p>{{ room.description }}</p>
                        <div>
                            <span>{{ room.host|stringformat:"s" }}</span>
                            <time datetime="{{ room.created_at|date:'Y-m-d' }}">(created at {{ room.created_at|naturaltime }})</time>
                        </div>
                    </div>
                    <div class="col-4">
                    {% if room.host.pk == user.pk %}
                        <div class="dropdown mt-2">
                            <a class="btn btn-outline-secondary btn-block dropdown-toggle" href="#" role="button"
                               id="dropdownMenuLink{{ forloop.counter }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               Control
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink{{ forloop.counter }}">
                                <a href="{% url 'chat:update_room' room.pk %}" class="dropdown-item">Update Room</a>
                                <a href="{% url 'chat:update_config' room.pk %}" class="dropdown-item">Update Config</a>
                                <div class="dropdown-divider"></div>
                                <button type="button" class="dropdown-item delete-room-modal-button"
                                        data-deleteurl="{% url 'chat:delete_room' room.pk %}">
                                    <span style="color: red">Delete</span>
                                </button>
                            </div>
                        </div>
                    {% endif %}
                    </div>
                </div>
            </article>
        {% empty %}
            <article>
                <p>No rooms exists.</p>
            </article>
        {% endfor %}
        </section>
    </div>
</div>
{% if rooms %}
<div class="row justify-content-center">
    <div class="col-12">
{% include "pagination.html" %}
    </div>
</div>
{% endif %}

{# define modal #}
<div class="modal" tabindex="-1" role="dialog" id="room-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirmation of deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>May I really delete this room ?</p>
            </div>
            <div class="modal-footer">
                <form action="" method="POST" id="delete-room-form">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Accept</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block bodyjs %}
<script>
(function() {
    const deleteRoomForm = document.querySelector('#delete-room-form');
    const deleteRoomModalButtons = document.querySelectorAll('.delete-room-modal-button');

    deleteRoomModalButtons.forEach((button) => {
        button.addEventListener('click', () => {
            deleteRoomForm.action = button.dataset.deleteurl;

            $('#room-modal').modal({
                backdrop: true,
                keyboard: true,
            });
        });
    });
}());
</script>
{% endblock %}

src/templates/chat/room_form.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center mb-1">
    <div class="col-12">
        <form method="POST">
            {% csrf_token %}

            <div class="form-row">
                <div class="col-12">
                    {{ form.as_p }}
                </div>
            </div>
            <div class="form-row mt-3">
                <div class="col-6">
                    <button type="submit" class="btn btn-primary btn-block">Register/Update</button>
                </div>
                <div class="col-6">
                    <a href="{% url 'chat:index' %}" class="btn btn-secondary btn-block">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}