src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('login/', views.LoginPage.as_view(), name='login'),
    path('logout/', views.LogoutPage.as_view(), name='logout'),
]

src/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create/room', views.CreateRoom.as_view(), name='create_room'),
    path('update/room/<int:pk>', views.UpdateRoom.as_view(), name='update_room'),
    path('delete/room/<int:pk>', views.DeleteRoom.as_view(), name='delete_room'),
    path('enter/room/<int:pk>', views.EnterRoom.as_view(), name='enter_room'),
    path('update/config/<int:pk>', views.UpdateConfig.as_view(), name='update_config'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('chat/', include('chat.urls', namespace='chat')),
]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils import timezone
from django.utils.translation import gettext_lazy

class CustomUserManager(UserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(email, password,  **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password,  **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    screen_name = models.CharField(
        gettext_lazy('screen name'),
        max_length=128,
        default='',
        blank=True,
        help_text=gettext_lazy('Option. 128 characters or fewer.'),
    )
    email = models.EmailField(gettext_lazy('E-mail address'), unique=True)
    is_staff = models.BooleanField(
        gettext_lazy('staff status'),
        default=False,
        help_text=gettext_lazy('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        gettext_lazy('active'),
        default=True,
        help_text=gettext_lazy(
            'Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(gettext_lazy('date joined'), default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = gettext_lazy('user')
        verbose_name_plural = gettext_lazy('users')

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return self.screen_name or self.email

src/accounts/views.py
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView

class Index(TemplateView):
    template_name = 'accounts/index.html'

class LoginPage(LoginView):
    template_name = 'accounts/login.html'

class LogoutPage(LogoutView):
    template_name = 'accounts/index.html'

src/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center">
    {% if user.is_authenticated  %}
    <div class="col-12">
        <div class="row">
            <h2 class="h2">{{ user|stringformat:"s" }}, welcome!</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card-columns">
                    <div class="card">
                        <div class="card-header">Chat</div>
                        <div class="card-body">
                            <a href="{% url 'chat:index' %}" class="btn btn-link btn-block" target="_self">
                                Chat
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <h5 class="h5">Plese login from the link above.</h5>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

src/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="card">
        <div class="card-body">
            <form action="{% url 'accounts:login' %}" method="POST">
                <div class="row">
                    <div class="col-12">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field.label }}
                        {{ field }}
                        {{ field.errors }}
                        <hr>
                    {% endfor %}
                    {% csrf_token %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                        <input type="hidden" name="next" value="{{ next }}" />
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                        <a href="{% url 'accounts:index' %}" class="btn btn-secondary btn-block">Back</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}